version: '3.4'

services:
  adonisapiapp:
    image: adonisapiapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 1337:1337
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
